name: bigdataproj
channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8=hd037594_8
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - icu=75.1=hfee45f7_0
  - libexpat=2.7.1=hec049ff_0
  - libffi=3.5.2=he5f378a_0
  - liblzma=5.8.1=h39f12f2_2
  - libsqlite=3.50.4=h4237e3c_0
  - libzlib=1.3.1=h8359307_2
  - ncurses=6.5=h5e97a16_3
  - openssl=3.5.4=h5503f6c_0
  - pip=25.2=pyh8b19718_0
  - python=3.10.19=hcd7f573_2_cpython
  - readline=8.2=h1d1bf99_2
  - setuptools=80.9.0=pyhff2d567_0
  - tk=8.6.13=h892fb3f_2
  - wheel=0.45.1=pyhd8ed1ab_1
  - pip:
      - boto3==1.40.66
      - botocore==1.40.66
      - certifi==2025.10.5
      - charset-normalizer==3.4.4
      - idna==3.11
      - jmespath==1.0.1
      - numpy==2.2.6
      - pandas==2.3.3
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - requests==2.32.5
      - s3transfer==0.14.0
      - six==1.17.0
      - tzdata==2025.2
      - urllib3==2.5.0
prefix: /Users/harrysocool/miniconda3/envs/bigdataproj
